# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true
- script: DEVELOPER_DIR=/Applications/Xcode_9.0.1.app xcodebuild -showsdks -json
  displayName: 'xcodebuild -showsdks -json'
- script: DEVELOPER_DIR=/Applications/Xcode_9.0.1.app xcrun simctl list -j devices
  displayName: 'xcrun simctl list -j devices'
- script: |
    DEVELOPER_DIR=/Applications/Xcode_9.0.1.app xcrun simctl list -j devices | python -c "import sys,json;print(' '.join(map(lambda x: x[0], filter(lambda x: len(filter(lambda y: y.get('availability') == '(available)', x[1])) > 0, json.load(sys.stdin)['devices'].items()))))"
  displayName: 'xcrun simctl list -j devices xcrun simctl list -j devices with python script'
- script: Pods/SwiftLint/swiftlint
  displayName: 'Runs SwiftLint'
- task: Xcode@5
  displayName: 'Run Unit Tests'
  inputs:
    actions: 'test'
    scheme: 'AppiumSwiftClientUnitTests'
    sdk: 'iphonesimulator'
    configuration: 'Debug'
    xcWorkspacePath: 'AppiumSwiftClient.xcworkspace'
    destinationTypeOption: 'simulators'
    destinationSimulators: 'iPhone 8'
    destinationPlatformOption: 'iOS'
    signingOption: 'auto'
    xcodeVersion: '10'
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'AppiumSwiftClient'
    sdk: 'iphoneos'
    configuration: 'Debug'
    xcWorkspacePath: 'AppiumSwiftClient.xcworkspace'
    xcodeVersion: '10'
