# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true
- script: Pods/SwiftLint/swiftlint
  displayName: 'Runs SwiftLint'
- task: Xcode@5
  displayName: 'Run Unit Tests'
  inputs:
    actions: 'test'
    scheme: 'AppiumSwiftClientUnitTests'
    sdk: 'iphonesimulator'
    configuration: 'Debug'
    xcWorkspacePath: 'AppiumSwiftClient.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    destinationTypeOption: 'simulators'
    destinationSimulators: 'iPhone 8'
    destinationPlatformOption: 'iOS'
    signingOption: "auto"
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'AppiumSwiftClient'
    sdk: 'iphoneos'
    configuration: 'Debug'
    xcWorkspacePath: 'AppiumSwiftClient.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
